program MetrodeCaracas;
uses crt;
var nombre, apellido, tipoboleto, cedula, linea: string[80];
	x, y , cantboletos, tipoviaje: integer;
		
begin	
		writeln ('   Te doy la bienvenida al Metro de Caracas.');
		writeln ('       ¿Desea adquirir algun boleto?');
		writeln ('             OPCION 01: SI');
		writeln ('             OPCION 02: NO');
		readln (x); 
				while (x <> 1) and (x <> 2) do
				begin
				clrscr;
				writeln ('Dato invalido. Intente de nuevo.');
				writeln ('   Te doy la bienvenida al Metro de Caracas.');
				writeln ('       ¿Desea adquirir algun boleto?');
				writeln ('             OPCION 01: SI');
				writeln ('             OPCION 02: NO');
				readln (x); 
				end;
					case x of
						2:begin
						clrscr;
						writeln ('A sido un placer. Vuelva pronto.');
						exit;
						end;
							1: begin
							clrscr;
							writeln ('Para proceder con su cotizacion, le vamos a pedir que nos otorgue los siguientes datos.');
							writeln ('         NOMBRE:');
							readln (nombre);
							writeln ('         APELLIDO:');
							readln (apellido);
							writeln ('         CEDULA DE IDENTIDAD.');
							readln (cedula);
							clrscr;
							writeln ('Para proseguir con su cotizacion, por favor, confirmar la validacion de sus datos.');
							writeln ();
							writeln ('Nombre: ',nombre);
							writeln ('Apellido: ',apellido);
							writeln ('Cedula: ',cedula);
							writeln ();
							writeln ('Presione 1 si todo es correcto.');
							writeln ('Presione 2 si existe un error y desea corregir.');
							readln (y);
										while (y <> 1) and (y <> 2) do
										begin
										clrscr;
										writeln ('Dato invalido. Intente de nuevo.');
										writeln ('         NOMBRE:');
										readln (nombre);
										writeln ('         APELLIDO:');
										readln (apellido);
										writeln ('         CEDULA DE IDENTIDAD.');
										readln (cedula);
										clrscr;
										writeln ('Para proseguir con su cotizacion, por favor, confirmar la validacion de sus datos.');
										writeln	();
										writeln ('Nombre: ',nombre);
										writeln ('Apellido: ',apellido);
										writeln ('Cedula: ',cedula);
										writeln ();
										writeln ('Presione 1 si todo es correcto.');
										writeln ('Presione 2 si existe un error y desea corregir.');
										readln (y);
										end;
												while y = 2 do 
												begin
												clrscr;
												writeln ('         NOMBRE:');
												readln (nombre);
												writeln ('         APELLIDO:');
												readln (apellido);
												writeln ('         CEDULA DE IDENTIDAD.');
												readln (cedula);
												clrscr;
												writeln ('Para proseguir con su cotizacion, por favor, confirmar la validacion de sus datos.');
												writeln	();
												writeln ('Nombre: ',nombre);
												writeln ('Apellido: ',apellido);
												writeln ('Cedula: ',cedula);
												writeln ();
												writeln ('Presione 1 si todo es correcto.');
												writeln ('Presione 2 si existe un error y desea corregir.');
												readln (y);
												end;
														if y = 1 then
														clrscr;
														writeln ('Por favor, indique la cantidad de boletos que desea comprar.');
														readln (cantboletos);
														writeln ('');
														clrscr;
														writeln ('     ¡Genial! Por favor, indique el tipo de boleto que desea adquirir');
														writeln ('segun las opciones que se mostraran a continuacion.');
														writeln ('');
														writeln ('');
														writeln ('');
														writeln ('     _____________________________________________________________________');
														writeln ('    |                 |                    |                              |');
														writeln ('    |    Boletos      |       Color        |          Cobertura           |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 1)  Simple      |     Amarillo       |      1 viaje en metro        |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |      1 viaje en metro        |');
														writeln ('    | 2) Integrado    |     Amarillo       |      1 viaje en metrobus     |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 3)Ida y vuelta  |     Amarillo       |      2 viajes en metro       |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 4)Ida y vuelta  |     Amarillo       |     2 viajes en metro        |');
														writeln ('    |   integrado     |                    |     2 viajes en metrobus     |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 5) MultiAbono   |      Naranja       |      10 viajes en metro      |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 6) MultiAbono   |      Naranja       |     10 viajes en metro       |');
														writeln ('    |    integrado    |                    |     10 viajes en metrobus    |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 7) Estudiantil  |        Azul        |      10 viajes en metro      |');
														writeln ('    |      Simple     |                    |                              |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 8) Estudiantil  |        Azul        |     10 viajes en metro       |');
														writeln ('    |    Integrado    |                    |     20 viajes en metrobus    |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    |                 |                    |           20 viajes          |');
														writeln ('    | 9)MetroTarjeta  |        Rojo        |           30 viajes          |');
														writeln ('    |                 |                    |           40 viajes          |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ('    |                 |                    |                              |');
														writeln ('    | 10)MetroTarjeta |                    | 20 viajes (Metro y Metrobus) |');
														writeln ('    |    Integrada    |        Rojo        | 30 viajes (Metro y Metrobus) |');
														writeln ('    |                 |                    | 40 viajes (Metro y Metrobus) |');
														writeln ('    |_________________|____________________|______________________________|');
														writeln ();
														readln (tipoboleto);
														writeln ('El monto total es: $',cantboletos*cantboletos/2:1:2);
																	while (tipoboleto <> '1') and (tipoboleto <> '2') and (tipoboleto <> '3') and (tipoboleto <> '4') and (tipoboleto <> '5') and (tipoboleto <> '6') and (tipoboleto <> '7') and (tipoboleto <> '8') and (tipoboleto <> '9') and (tipoboleto <> '10') do 
																	begin
																	clrscr;
																	writeln ('Dato invalido. Intente de nuevo.');
																	writeln ('');
																	writeln ('');
																	writeln ('');
																	writeln ('     _____________________________________________________________________');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    |    Boletos      |       Color        |          Cobertura           |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 1)  Simple      |     Amarillo       |      1 viaje en metro        |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |      1 viaje en metro        |');
																	writeln ('    | 2) Integrado    |     Amarillo       |      1 viaje en metrobus     |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 3)Ida y vuelta  |     Amarillo       |      2 viajes en metro       |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 4)Ida y vuelta  |     Amarillo       |     2 viajes en metro        |');
																	writeln ('    |   integrado     |                    |     2 viajes en metrobus     |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 5) MultiAbono   |      Naranja       |      10 viajes en metro      |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 6) MultiAbono   |      Naranja       |     10 viajes en metro       |');
																	writeln ('    |    integrado    |                    |     10 viajes en metrobus    |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 7) Estudiantil  |        Azul        |      10 viajes en metro      |');
																	writeln ('    |      Simple     |                    |                              |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 8) Estudiantil  |        Azul        |     10 viajes en metro       |');
																	writeln ('    |    Integrado    |                    |     20 viajes en metrobus    |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    |                 |                    |           20 viajes          |');
																	writeln ('    | 9)MetroTarjeta  |        Rojo        |           30 viajes          |');
																	writeln ('    |                 |                    |           40 viajes          |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ('    |                 |                    |                              |');
																	writeln ('    | 10)MetroTarjeta |                    | 20 viajes (Metro y Metrobus) |');
																	writeln ('    |    Integrada    |        Rojo        | 30 viajes (Metro y Metrobus) |');
																	writeln ('    |                 |                    | 40 viajes (Metro y Metrobus) |');
																	writeln ('    |_________________|____________________|______________________________|');
																	writeln ();
																	readln (tipoboleto);
																	end;
																			clrscr;
																			writeln ('');
																			writeln ('');
																			writeln ('Por favor, describa el tipo de viaje que desea realizar.');
																			writeln ('');
																			writeln ('OPCION 01: Viaje en metro.');
																			writeln ('OPCION 02: Viaje en metrobus.');
																			readln (tipoviaje);
																				case tipoviaje of
																					1: begin
																					writeln ('El monto total es: $',cantboletos*tipoviaje);
																					writeln ('');
																					writeln ('Por favor seleccione la linea en la que desea viajar');
																					writeln ('');
																					writeln ('');
																					writeln ('');
																					writeln ('     _______');
																					writeln ('    |LINEA 1|_______________________________________________________________________________________ ');
																					writeln ('    | - Propatria                   | - Parque Carabobo             | - Altamira                    |');          
																					writeln ('    | - Perez Bonalde               | - Bellas Artes                | - Miranda                     |');
																					writeln ('    | - Plaza Zucre                 | - Colegio de Ingenieros       | - Los Dos Caminos             |');
																					writeln ('    | - Gato Negro                  | - Plaza Venezuela             | - Los Cortijos                |');
																					writeln ('    | - Agua Salud                  | - Sabana Grande               | - La California               |');
																					writeln ('    | - Cabo Amarillo               | - Chacaito                    | - Petare                      |');
																					writeln ('    | - Capitolio                   | - Chacao                      | - Palo Verde                  |');
																					writeln ('    | - La Hoyada                   |                               |                               |');
																					writeln ('    |_______________________________|_______________________________|_______________________________|');
																					writeln ('     _______');
																					writeln ('    |LINEA 2|_______________________________________________________________________________________ ');
																					writeln ('    | - El silencio                 | - La Paz                      | - Mamera                      |');          
																					writeln ('    | - Capuchinos                  | - La Yaguara                  | - Caricuao                    |');
																					writeln ('    | - Maternidad                  | - Carapita                    | - Zoologico                   |');
																					writeln ('    | - Artiguas                    | - Antimano                    | - Luis Pineda / Las adjuntas  |');
																					writeln ('    |_______________________________|_______________________________|_______________________________|');
																					writeln ('     _______');
																					writeln ('    |LINEA 3|_______________________________________________________________________________________ ');
																					writeln ('    | - Plaza Venezuela             | - La Bandera                  | - Coche                       |');          
																					writeln ('    | - Ciudad Universitaria        | - El Valle                    | - Mercado                     |');
																					writeln ('    | - Los Simbolos                | - Los Jardines                | - La Rinconada                |');
																					writeln ('    |_______________________________|_______________________________|_______________________________|');
																					writeln ('     _______');
																					writeln ('    |LINEA 4|_______________________________________________________________________________________ ');
																					writeln ('    | - Zona Rental                 | - Materniadad                 | - Antimano                    |');          
																					writeln ('    | - Parque Central              | - Artigas                     | - Mamera                      |');
																					writeln ('    | - Nuevo Circo                 | - La Paz                      | - Luis Pineda / Las adjuntas  |');
																					writeln ('    | - Teatros                     | - La Yaguara                  |                               |');
																					writeln ('    | - Capuchino                   | - Carapita                    |                               |');
																					writeln ('    |_______________________________|_______________________________|_______________________________|');
																					writeln ('     _______');
																					writeln ('    |LINEA 5|_______________________________________________________________________________________ ');
																					writeln ('    | - Bello Monte                 | - Bello Campo                 | - Boleita                     |');          
																					writeln ('    | - Las Mercedes                | - Hugo Chavez                 | - El Marquez                  |');
																					writeln ('    | - Parque Simon Bolivar        | - Montecristo                 | - Warairarepano               |');
																					writeln ('    |_______________________________|_______________________________|_______________________________|');
																					writeln ('     _______');
																					writeln ('    |LINEA 6|_______________________________________________________');
																					writeln ('    | - Zoologico                   | - La Rinconada                |'); 
																					writeln ('    |_______________________________|_______________________________|');
																					writeln ('     _______');
																					writeln ('    |LINEA 7|_______________________________________________________________________________________ ');
																					writeln ('    | - Las Flores                  | - El Cristo                   | - Roosevelt                   |');          
																					writeln ('    | - Panteon                     | - Roca Tarpeya                | - La Bandera                  |');
																					writeln ('    | - Socorro                     | - Presidente Medina           | - Los Ilustres                |');
																					writeln ('    | - La Hoyada                   | - INCES                       |                               |');
																					writeln ('    |_______________________________|_______________________________|_______________________________|');
																					writeln ('     _______');
																					writeln ('    |CLABETREN|_____________________________________________________________________________________ ');
																					writeln ('    | - Petare 2                    | - 5 de Julio                  | - Warairarepano               |');          
																					writeln ('    | - 19 de Abril                 | - 24 de Julio                 |                               |');
																					writeln ('    |_______________________________|_______________________________|_______________________________|');
																					writeln ();
																					readln (linea);
																					end;
																							2: begin
																							writeln ('El monto total es: $',cantboletos*tipoviaje/4:1:2);
																							writeln ('');
																							writeln ('Por favor seleccione la linea en la que desea viajar');
																							writeln ('');
																							writeln ('');
																							writeln ('');
																							writeln ('     _______');
																							writeln ('    |LINEA 1|_______________________________________________________________________________________ ');
																							writeln ('    | - Propatria                   | - Parque Carabobo             | - Altamira                    |');          
																							writeln ('    | - Perez Bonalde               | - Bellas Artes                | - Miranda                     |');
																							writeln ('    | - Plaza Zucre                 | - Colegio de Ingenieros       | - Los Dos Caminos             |');
																							writeln ('    | - Gato Negro                  | - Plaza Venezuela             | - Los Cortijos                |');
																							writeln ('    | - Agua Salud                  | - Sabana Grande               | - La California               |');
																							writeln ('    | - Cabo Amarillo               | - Chacaito                    | - Petare                      |');
																							writeln ('    | - Capitolio                   | - Chacao                      | - Palo Verde                  |');
																							writeln ('    | - La Hoyada                   |                               |                               |');
																							writeln ('    |_______________________________|_______________________________|_______________________________|');
																							writeln ('     _______');
																							writeln ('    |LINEA 2|_______________________________________________________________________________________ ');
																							writeln ('    | - El silencio                 | - La Paz                      | - Mamera                      |');          
																							writeln ('    | - Capuchinos                  | - La Yaguara                  | - Caricuao                    |');
																							writeln ('    | - Maternidad                  | - Carapita                    | - Zoologico                   |');
																							writeln ('    | - Artiguas                    | - Antimano                    | - Luis Pineda / Las adjuntas  |');
																							writeln ('    |_______________________________|_______________________________|_______________________________|');
																							writeln ('     _______');
																							writeln ('    |LINEA 3|_______________________________________________________________________________________ ');
																							writeln ('    | - Plaza Venezuela             | - La Bandera                  | - Coche                       |');          
																							writeln ('    | - Ciudad Universitaria        | - El Valle                    | - Mercado                     |');
																							writeln ('    | - Los Simbolos                | - Los Jardines                | - La Rinconada                |');
																							writeln ('    |_______________________________|_______________________________|_______________________________|');
																							writeln ('     _______');
																							writeln ('    |LINEA 4|_______________________________________________________________________________________ ');
																							writeln ('    | - Zona Rental                 | - Materniadad                 | - Antimano                    |');          
																							writeln ('    | - Parque Central              | - Artigas                     | - Mamera                      |');
																							writeln ('    | - Nuevo Circo                 | - La Paz                      | - Luis Pineda / Las adjuntas  |');
																							writeln ('    | - Teatros                     | - La Yaguara                  |                               |');
																							writeln ('    | - Capuchino                   | - Carapita                    |                               |');
																							writeln ('    |_______________________________|_______________________________|_______________________________|');
																							writeln ('     _______');
																							writeln ('    |LINEA 5|_______________________________________________________________________________________ ');
																							writeln ('    | - Bello Monte                 | - Bello Campo                 | - Boleita                     |');          
																							writeln ('    | - Las Mercedes                | - Hugo Chavez                 | - El Marquez                  |');
																							writeln ('    | - Parque Simon Bolivar        | - Montecristo                 | - Warairarepano               |');
																							writeln ('    |_______________________________|_______________________________|_______________________________|');
																							writeln ('     _______');
																							writeln ('    |LINEA 6|_______________________________________________________');
																							writeln ('    | - Zoologico                   | - La Rinconada                |'); 
																							writeln ('    |_______________________________|_______________________________|');
																							writeln ('     _______');
																							writeln ('    |LINEA 7|_______________________________________________________________________________________ ');
																							writeln ('    | - Las Flores                  | - El Cristo                   | - Roosevelt                   |');          
																							writeln ('    | - Panteon                     | - Roca Tarpeya                | - La Bandera                  |');
																							writeln ('    | - Socorro                     | - Presidente Medina           | - Los Ilustres                |');
																							writeln ('    | - La Hoyada                   | - INCES                       |                               |');
																							writeln ('    |_______________________________|_______________________________|_______________________________|');
																							writeln ('     _______');
																							writeln ('    |CLABETREN|_____________________________________________________________________________________ ');
																							writeln ('    | - Petare 2                    | - 5 de Julio                  | - Warairarepano               |');          
																							writeln ('    | - 19 de Abril                 | - 24 de Julio                 |                               |');
																							writeln ('    |_______________________________|_______________________________|_______________________________|');
																							writeln ();
																							readln (linea);
																										while (x <> 1) and (x <> 2) do
																										begin
																										clrscr;
																										writeln ('Dato invalido. Intente de nuevo.');
																										writeln ('');
																										writeln ('');
																										writeln ('Por favor, describa el tipo de viaje que desea realizar.');
																										writeln ('');
																										writeln ('OPCION 01: Viaje en metro.');
																										writeln ('OPCION 02: Viaje en metrobus.');
																										readln (tipoviaje);																												
																										end;
																												
													end;
end;
end;
end;
end.
